export const jobs = [
  {
    id: 1,
    title: "Senior UI/UX Designer",
    company: "Amazon",
    location: "San Francisco, CA",
    remote: false,
    category: "Frontend",
    salary: "42 LPA",
    type: "Part-time",
    posted: "5 days ago",
    logo: "/logos/amazon.png",
    tags: ["Part-time", "Senior level"],
  },
  {
    id: 2,
    title: "Graphic Designer",
    company: "Google",
    location: "Mountain View, CA",
    remote: false,
    category: "Frontend",
    salary: "55 - 80 LPA",
    type: "Full-time",
    posted: "30 days ago",
    logo: "/logos/google.png",
    tags: ["Full-time", "Flexible schedule"],
  },
  {
    id: 3,
    title: "Senior Motion Designer",
    company: "Dribbble",
    location: "San Francisco, CA",
    remote: true,
    category: "Remote",
    salary: "30 LPA",
    type: "Contract",
    posted: "18 days ago",
    logo: "/logos/dribbble.png",
    tags: ["Contract", "Remote"],
  },
  {
    id: 4,
    title: "UX Designer",
    company: "Meta",
    location: "New York, NY",
    remote: false,
    category: "Frontend",
    salary: "70 - 95 LPA",
    type: "Full-time",
    posted: "3 months ago",
    logo: "/logos/meta.png",
    tags: ["Full-time", "In office"],
  },
  {
    id: 5,
    title: "Junior UX/UI Designer",
    company: "Airbnb",
    location: "San Francisco, CA",
    remote: true,
    category: "Internship",
    salary: "35 LPA",
    type: "Contract",
    posted: "1 day ago",
    logo: "/logos/airbnb.png",
    tags: ["Contract", "Remote"],
  },
  {
    id: 6,
    title: "Backend Engineer",
    company: "Apple",
    location: "Cupertino, CA",
    remote: false,
    category: "Backend",
    salary: "28 - 42 LPA",
    type: "Full-time",
    posted: "6 days ago",
    logo: "/logos/apple.png",
    tags: ["Full-time", "In office"],
  },
];
